name: pull_request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_VERSIONS: "['16', '18', 'lts/*', 'latest']"

jobs:
  test-unix:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(env.NODE_VERSIONS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
